apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: cjwnbhf9q-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-5fa93841b2.bfvd.p3.openshiftapps.com/rhtap/rhtap-qe:7653d81db2c3fd8a74f104daef6300c85c82b77d@sha256:b5a9b4db7d5160ed4c1725d93b7d4b5d3d2ea7bfed939a9d1ecb1ec2c095ef39
        name: container-image  
